### ISSUE TITLE
QUESTION: Is there the kernel for Umidigi A5 Pro?

### ISSUE THREAD

**Issue by hradec** [Hadenix/vendor_treble_encryptable_umidigi_a5_pro#1]
I'm looking to buy a phone that I can update myself in the future... I'm so F#$@ tired of those mediocre policies of forcing you to buy a new device just by refusing to release the new version of an OS...

I want to have the option of build my own OS version for my phone, so I can update it myself in the future, if the company won't release a newer version of the OS. (and it will probably won't for chinese phones)

So, if this is the kernel for Umidi A5 Pro, I'll definitely buy one for myself, since I can use this kernel with newer versions of android, and even upgrade this kernel in the future if needed. 

thanks for now... 

-H

**Comment by Hadenix** [comment]
@hradec We are working on making custom firmware for this phone.
